image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: Build and Push Docker Image
        services:
          - docker
        caches:
          - docker
        script:
          # Authenticate with Docker Hub using environment variables
          - export DOCKERHUB_USERNAME=andonebekasi
          - export DOCKERHUB_PASSWORD=Akuqwe123$

          # Log in to Docker Hub
          - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

          # Build the Docker image
          - docker build -t andonebekasi/my-nodejs-static-website .

          # Push the Docker image to Docker Hub
          - docker push andonebekasi/my-nodejs-static-website:latest
