image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        name: Build and Push Docker Image
        services:
          - docker
        caches:
          - docker
        script:
          # Authenticate with Docker Hub using environment variables
          - export DOCKERHUB_USERNAME=isi-username
          - export DOCKERHUB_PASSWORD=isi-password

          # Log in to Docker Hub
          - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

          # Build the Docker image
          - docker build -t andonebekasi/go-simple-web-static:latest .

          # Push the Docker image to Docker Hub
          - docker push andonebekasi/go-simple-web-static:latest
