apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  selector:
    matchLabels:
      app: go
  replicas: 3
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: andonebekasi/go-simple-web-static
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
